all:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Wall -Werror -std=c99 -o main main.c -lm
all2:
	gcc -g3 -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -Wall -Werror -std=c99 -o main-2 main-2.c -lm
run:
	./main
run2:
	./main-2